package com.ecommerce.service;

import com.ecommerce.controller.dto.CreateOrderRequest;
import com.ecommerce.controller.dto.OrderResponse;
import com.ecommerce.domain.*;
import com.ecommerce.exception.DuplicateOrderException;
import com.ecommerce.exception.OrderNotFoundException;
import com.ecommerce.messaging.OrderEventPublisher;
import com.ecommerce.messaging.events.OrderCreatedEvent;
import com.ecommerce.messaging.events.PaymentFailedEvent;
import com.ecommerce.messaging.events.PaymentProcessedEvent;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class OrderService {

    private final OrderRepository orderRepository;
    private final OrderEventPublisher eventPublisher;
    private final ProductCatalogService productCatalogService;
    private final OutboxEventRepository outboxEventRepository;
    private final ObjectMapper objectMapper;


    /**
     * Creates a new order resolving all server-side fields:
     *   - customerId     → comes from the caller (extracted from header/JWT in controller)
     *   - idempotencyKey → autogenerated if not provided by client
     *   - productName    → resolved from ProductCatalogService
     *   - unitPrice      → resolved from ProductCatalogService (client cannot set prices)
     */
    @Transactional
    public OrderResponse createOrder(String customerId, String customerEmail, CreateOrderRequest request) {


        // ── Autogenerate idempotencyKey if client didn't send one ─────────────
        String idempotencyKey = (request.getIdempotencyKey() != null && !request.getIdempotencyKey().isBlank())
                ? request.getIdempotencyKey()
                : UUID.randomUUID().toString();

        log.info("[ORDER-SERVICE] Creating order | customerId={} | idempotencyKey={} | items={}",
                customerId, idempotencyKey, request.getItems().size());

        // ── Idempotency check ─────────────────────────────────────────────────
        if (orderRepository.existsByIdempotencyKey(idempotencyKey)) {
            log.warn("[ORDER-SERVICE] Duplicate request | idempotencyKey={}", idempotencyKey);
            throw new DuplicateOrderException(
                    "Order with idempotency key already exists: " + idempotencyKey);
        }

        // ── Build order items resolving name + price from catalog ─────────────
        Order order = Order.builder()
                .customerId(customerId)
                .customerEmail(customerEmail)
                .currency(request.getCurrency())
                .idempotencyKey(idempotencyKey)
                .build();

        List<OrderItem> items = request.getItems().stream()
                .map(itemReq -> {
                    // Server resolves name and price — client only sent productId + quantity
                    ProductCatalogService.ProductInfo product =
                            productCatalogService.resolve(itemReq.getProductId());

                    return OrderItem.builder()
                            .productId(itemReq.getProductId())
                            .productName(product.name())     // ← from catalog
                            .quantity(itemReq.getQuantity())
                            .unitPrice(product.price())      // ← from catalog, not from client
                            .build();
                })
                .collect(Collectors.toList());

        items.forEach(order::addItem);

        // ── Calculate total ───────────────────────────────────────────────────
        BigDecimal total = items.stream()
                .map(item -> item.getUnitPrice().multiply(BigDecimal.valueOf(item.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        order.setTotalAmount(total);
        order.setStatus(OrderStatus.PENDING);

        Order savedOrder = orderRepository.save(order);
        log.info("[ORDER-SERVICE] Order persisted | orderId={} | total={} {}",
                savedOrder.getOrderId(), total, request.getCurrency());

        // ── Publish OrderCreated event ────────────────────────────────────────
        OrderCreatedEvent event = buildOrderCreatedEvent(savedOrder);

        try {
            OutboxEvent outboxEvent = OutboxEvent.builder()
                    .eventId(event.getEventId())
                    .eventType("ORDER_CREATED")
                    .payload(objectMapper.writeValueAsString(event))
                    .status(OutboxStatus.PENDING)
                    .build();

            outboxEventRepository.save(outboxEvent);
            log.info("[ORDER-SERVICE] OutboxEvent guardado | eventId={}", event.getEventId());

        } catch (JsonProcessingException e) {
            log.error("[ORDER-SERVICE] Error serializando OutboxEvent | orderId={}", savedOrder.getOrderId(), e);
            throw new RuntimeException("Error al serializar el evento de orden", e);
        }

        savedOrder.markAsPaymentProcessing();
        orderRepository.save(savedOrder);

        return OrderResponse.from(savedOrder);
    }

    @Transactional
    public void handlePaymentProcessed(PaymentProcessedEvent event) {
        log.info("[ORDER-SERVICE] Updating order to PAID | orderId={}", event.getOrderId());

        Order order = orderRepository.findByOrderId(event.getOrderId())
                .orElseThrow(() -> new OrderNotFoundException("Order not found: " + event.getOrderId()));

        order.markAsPaid(event.getPaymentId());
        orderRepository.save(order);

        log.info("[ORDER-SERVICE] Order status updated to PAID | orderId={}", order.getOrderId());
    }

    @Transactional
    public void handlePaymentFailed(PaymentFailedEvent event) {
        log.info("[ORDER-SERVICE] Updating order to PAYMENT_FAILED | orderId={} | reason={}",
                event.getOrderId(), event.getFailureReason());

        Order order = orderRepository.findByOrderId(event.getOrderId())
                .orElseThrow(() -> new OrderNotFoundException("Order not found: " + event.getOrderId()));

        order.markAsPaymentFailed(event.getFailureReason());
        orderRepository.save(order);

        log.info("[ORDER-SERVICE] Order status updated to PAYMENT_FAILED | orderId={}", order.getOrderId());
    }

    @Transactional(readOnly = true)
    public OrderResponse getOrder(String orderId) {
        Order order = orderRepository.findByOrderId(orderId)
                .orElseThrow(() -> new OrderNotFoundException("Order not found: " + orderId));
        return OrderResponse.from(order);
    }

    private OrderCreatedEvent buildOrderCreatedEvent(Order order) {

        List<OrderCreatedEvent.OrderItemDto> itemDtos = order.getItems().stream()
                .map(item -> OrderCreatedEvent.OrderItemDto.builder()
                        .productId(item.getProductId())
                        .productName(item.getProductName())
                        .quantity(item.getQuantity())
                        .unitPrice(item.getUnitPrice())
                        .subtotal(item.getSubtotal())
                        .build())
                .collect(Collectors.toList());

        return OrderCreatedEvent.builder()
                .orderId(order.getOrderId())
                .customerId(order.getCustomerId())
                .customerEmail(order.getCustomerEmail())
                .totalAmount(order.getTotalAmount())
                .currency(order.getCurrency())
                .items(itemDtos)
                .build();

//        // 👇 romper serialización a propósito
//        event.setNonSerializable(new Object() {
//            public String getBroken() {
//                throw new RuntimeException("boom");
//            }
//        });

    }
}
