package com.ecommerce.config;

import com.ecommerce.domain.Product;
import com.ecommerce.domain.ProductRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.io.Resource;
import org.springframework.core.io.ResourceLoader;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.Reader;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;

/**
 * Loads the product catalog from a CSV file at startup.
 *
 * <p>Design notes:
 * <ul>
 *   <li>The CSV location is configurable via {@code app.catalog.csv-location}
 *       (a Spring Resource string; classpath or file).</li>
 *   <li>Import is an UPSERT keyed by {@code productId}: insert when the business key
 *       is new, update the mutable fields when it already exists. This is idempotent
 *       across restarts (no duplicates) and picks up catalog edits.</li>
 *   <li>The CSV {@code id} column is intentionally ignored: {@code id} is the internal
 *       technical PK and is always generated by the database, never trusted from the CSV.</li>
 *   <li>Each row is validated against the domain invariants; invalid rows are logged
 *       and skipped (non-fatal) so one bad row cannot abort the whole import.</li>
 * </ul>
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class CatalogCsvLoader implements ApplicationRunner {

    // These MUST be final so Lombok's @RequiredArgsConstructor injects them.
    // The original code left the repository non-final, so it was never injected
    // and produced a NullPointerException on startup.
    private final ProductRepository productRepository;
    private final ResourceLoader resourceLoader;

    @Value("${app.catalog.csv-location:classpath:products_300.csv}")
    private String csvLocation;

    @Override
    @Transactional
    public void run(ApplicationArguments args) {
        Resource resource = resourceLoader.getResource(csvLocation);
        if (!resource.exists()) {
            log.error("[PRODUCT-SERVICE] Catalog CSV not found at '{}'. Skipping import.", csvLocation);
            return;
        }

        log.info("[PRODUCT-SERVICE] Importing catalog from '{}'...", csvLocation);
        int inserted = 0;
        int updated = 0;
        int skipped = 0;
        long rowNumber = 1; // header is row 1

        CSVFormat format = CSVFormat.DEFAULT.builder()
                .setHeader()
                .setSkipHeaderRecord(true)
                .setIgnoreHeaderCase(true)
                .setTrim(true)
                .build();

        try (Reader reader = new BufferedReader(
                new InputStreamReader(resource.getInputStream(), StandardCharsets.UTF_8));
             CSVParser parser = CSVParser.parse(reader, format)) {

            for (CSVRecord record : parser) {
                rowNumber++;
                try {
                    ParsedRow row = parseAndValidate(record);
                    boolean isUpdate = upsert(row);
                    if (isUpdate) {
                        updated++;
                    } else {
                        inserted++;
                    }
                } catch (RowValidationException ex) {
                    skipped++;
                    log.warn("[PRODUCT-SERVICE] Skipping invalid CSV row {} | {}", rowNumber, ex.getMessage());
                }
            }
        } catch (Exception e) {
            log.error("[PRODUCT-SERVICE] Fatal error reading catalog CSV", e);
            return;
        }

        log.info("[PRODUCT-SERVICE] Catalog import finished | inserted={} | updated={} | skipped={}",
                inserted, updated, skipped);
    }

    /** Upsert by business key. Returns true if an existing product was updated. */
    private boolean upsert(ParsedRow row) {
        return productRepository.findByProductId(row.productId())
                .map(existing -> {
                    // productId is immutable; update the mutable fields only.
                    existing.setName(row.name());
                    existing.setPrice(row.price());
                    existing.setStock(row.stock());
                    existing.setActive(row.active());
                    productRepository.save(existing);
                    return true;
                })
                .orElseGet(() -> {
                    Product product = Product.builder()
                            .productId(row.productId())
                            .name(row.name())
                            .price(row.price())
                            .stock(row.stock())
                            .active(row.active())
                            .build();
                    productRepository.save(product);
                    return false;
                });
    }

    /**
     * Parse a CSV record and enforce the domain invariants.
     * NOTE: the CSV header uses "active" (not "is_active"); the "id" column is ignored.
     */
    private ParsedRow parseAndValidate(CSVRecord record) {
        String productId = record.isMapped("productId") ? record.get("productId") : null;
        String name = record.isMapped("name") ? record.get("name") : null;
        String rawPrice = record.isMapped("price") ? record.get("price") : null;
        String rawStock = record.isMapped("stock") ? record.get("stock") : null;
        String rawActive = record.isMapped("active") ? record.get("active") : "true";

        if (productId == null || productId.isBlank()) {
            throw new RowValidationException("productId is required");
        }
        if (name == null || name.length() < 3 || name.length() > 150) {
            throw new RowValidationException("name must be 3-150 chars (was '" + name + "')");
        }

        BigDecimal price;
        try {
            price = new BigDecimal(rawPrice);
        } catch (NumberFormatException e) {
            throw new RowValidationException("price is not a number (was '" + rawPrice + "')");
        }
        if (price.compareTo(BigDecimal.ZERO) <= 0) {
            throw new RowValidationException("price must be > 0 (was '" + rawPrice + "')");
        }

        int stock;
        try {
            stock = Integer.parseInt(rawStock);
        } catch (NumberFormatException e) {
            throw new RowValidationException("stock is not an integer (was '" + rawStock + "')");
        }
        if (stock < 0) {
            throw new RowValidationException("stock must be >= 0 (was '" + rawStock + "')");
        }

        boolean active = Boolean.parseBoolean(rawActive);
        return new ParsedRow(productId, name, price, stock, active);
    }

    /** Immutable, already-validated view of a CSV row. */
    private record ParsedRow(String productId, String name, BigDecimal price, int stock, boolean active) {
    }

    /** Signals that a single row failed validation and must be skipped. */
    private static class RowValidationException extends RuntimeException {
        RowValidationException(String message) {
            super(message);
        }
    }
}
