apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: ecommerce
data:
  MYSQL_HOST: order-db
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  PRODUCT_SERVICE_URL: http://product-service:8085
  AUTH_SERVICE_URL: http://auth-service:8084
  ZIPKIN_HOST: zipkin
