apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: ecommerce
data:
  MYSQL_HOST: notification-db
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  MAIL_ENABLED: "false"
  ZIPKIN_HOST: zipkin
